/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "admin.login": [],
    "admin.login.post": [],
    "admin.logout": [],
    "admin.edit-profile-form": [],
    "admin.admin-settings.toggle-active": [],
    "admin.admin-settings": [],
    "admin.admin-settings.store": [],
    "admin.admin-settings.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.admin-settings.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.admin-settings.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.administration-settings.add": [],
    "admin.administration-settings.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.administration-settings": [],
    "admin.administration-settings.store": [],
    "admin.administration-settings.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.administration-settings.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.administration-settings.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.basic-website-settings": [],
    "admin.dashboard": []
}
}
export {};
