url = "http://yungtay.vjinc.biz/api/v1/history-orders"
request = "POST"
header = "Accept: application/json"
form = "order_name=日立永大_李小名"
form = "customer_name=李小名"
form = "contact_phone=0972872972"
form = "contact_email=lee@vjinc.biz"
form = "case_area=106"
form = "series_model=EAS"
form = "cabin_specs[ceiling]=CH5 / J147"
form = "cabin_specs[door_panel]=髮紋不鏽鋼"
form = "cabin_specs[side_panel_left]=EAS / C114 / A111 / C114"
form = "cabin_specs[side_panel_right]=EAS / C114 / A111 / C114"
form = "cabin_specs[side_panel_back]=EAS / C114 / A111 / C114"
form = "cabin_specs[side_panel_front]=SNW-9"
form = "cabin_specs[floor]=單一材質 / 505"
form = "cabin_specs[control_panel]=KF-D2F"
form = "cabin_specs[handrail]=None"
form = "cabin_specs[trim]=None"
form = "entrance_specs[door_panel]=1072"
form = "entrance_specs[door_frame]=窄型門框 / 髮紋不鏽鋼"
form = "entrance_specs[lantern]=None"
form = "entrance_specs[control_panel]=HOT LED"
form = "elevator_image=@elevatorPNG/elv-test.png"
